server:
  port: 8082
  servlet:
    context-path: /client

spring:
  application:
    name: springboot-admin-client
  boot:
    admin:
      client:
        url: http://127.0.0.1:8081/admin
        username: admin
        password: 123456


management:
  endpoints:
    web:
      exposure:
        include: '*'